### ISSUE TITLE
支持传入变量如当前文档id

### ISSUE THREAD

**Issue by winter60** [frostime/sy-bookmark-plus#14]
F佬， 有一个好玩的玩法， sql 支持传入当前文档id，sql如：
```sql
xxxxxxx where xxxx= '{{current_root_id}})'

```

`{{current_root_id}}`  在执行sql前替换成当前文档id , 这样很多跟当前文档有关的查询就能写，如正反链、父子兄弟文档等等 , 另外切换文当时，带变量的sql要重新执行。如果能支持，可能会很好玩~❤️

**Comment by hqweay** [comment]
附议，这样会很好玩！
我想到的场景是通过书签+来实现在右侧面板展示当前活动文档的标注。
另外有可能在插件面板实现反链面板的展示吗？（可编辑）

**Comment by frostime** [comment]
> 附议，这样会很好玩！ 我想到的场景是通过书签+来实现在右侧面板展示当前活动文档的标注。 另外有可能在插件面板实现反链面板的展示吗？（可编辑）

书签插件只做项目的罗列，不会涉及详细内容的展示和编辑。

如果有展示、编辑内容的需求，可以和文档流插件搭配使用。

**Comment by hqweay** [comment]
> > 附议，这样会很好玩！ 我想到的场景是通过书签+来实现在右侧面板展示当前活动文档的标注。 另外有可能在插件面板实现反链面板的展示吗？（可编辑）
> 
> 书签插件只做项目的罗列，不会涉及详细内容的展示和编辑。
> 
> 如果有展示、编辑内容的需求，可以和文档流插件搭配使用。

这样啊，谢谢F～！

**Comment by winter60** [comment]
太棒了，F佬

> 另外切换文档时，带变量的sql要重新执行

有CurDocId  CurRootId变量的sql需要重新执行下 ，看能否优化下？

**Comment by frostime** [comment]
> 太棒了，F佬 @frostime
> 
> > 另外切换文档时，带变量的sql要重新执行
> 
> 有CurDocId CurRootId变量的sql需要重新执行下 ，看能否优化下？

这需要额外改一些功能的实现方式，你单开一个 issue 吧。
