### ISSUE TITLE
书签图标不见了？

### ISSUE THREAD

**Issue by sweesalt** [frostime/sy-bookmark-plus#15]
早上打开电脑，发现书签图标不见了，按 Alt+3 也没有反应。

**Comment by sweesalt** [comment]
重启思源，图标回来了

**Comment by frostime** [comment]
运行过程中没的？有做过什么特殊操作吗？

请看一下能否复现，否则无法确定是否是插件的问题，更无法定位问题。

**Comment by frostime** [comment]
本 issue 先关闭了；如果还有问题请再提出。
