### ISSUE TITLE
悬浮显示块的 ariaLabel

### ISSUE THREAD

**Issue by leeyaunlong** [frostime/sy-bookmark-plus#18]
动态查询出来的行内容比较长,能在面板中提供悬浮提示内容吗?
实际行的内容都查出来了, 只是因为面板宽度只会看到很少一部分,
能跟其他面板一样提供鼠标悬浮到行上,显示完整(抓到的内容)的提示框吗?

**Comment by frostime** [comment]
你把鼠标悬浮在前面的图标上是会自动弹出完整的块内容的啊。

![image](https://github.com/user-attachments/assets/69bd2651-9a75-47ea-bd4a-43851dea75c5)
