### ISSUE TITLE
无法同步

### ISSUE THREAD

**Issue by primejava** [frostime/sy-bookmark-plus#25]
您好，我基于minio自建的同步，发现在家创建的普通书签组，无法同步到公司的思源笔记

**Comment by frostime** [comment]
能明确同步失败的触发方式吗？

因为我目前是没有遇到过这种问题的，你只说一个同步失败的话，我也没法定位问题的所在。

另外你可以看一下数据快照对比，找到 bookmark.json ，看看到底发生了什么变化。

![image](https://github.com/user-attachments/assets/eec29034-c958-417e-86ab-ad0eee582814)

----

**如果你没那么多闲空，只想要快速把书签同步到你公司的思源笔记里面的话**。有一个方案是，把你家里面的思源笔记工作空间中如下目录的文件复制到公司的思源笔记里面。
复制之前有必要先关闭公司里面的思源笔记运行进程（或者至少禁用Bookmark插件），等待复制完毕之后再重启思源笔记。

![image](https://github.com/user-attachments/assets/5fcf267b-437b-40f9-8a5b-bfa72e13006c)

**Comment by primejava** [comment]
![image](https://github.com/user-attachments/assets/3434a3b8-fdcf-426f-905e-7a9c9dc6d4aa)
你好我对比了一下，发现实际上文件内容已经成功同步了过来，只是显示不出来

**Comment by frostime** [comment]
> ![image](https://private-user-images.githubusercontent.com/10646824/356949202-3434a3b8-fdcf-426f-905e-7a9c9dc6d4aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDM5NjksIm5iZiI6MTcyMzQ0MzY2OSwicGF0aCI6Ii8xMDY0NjgyNC8zNTY5NDkyMDItMzQzNGEzYjgtZmRjZi00MjZmLTkwNWUtN2E5YzlkYzZkNGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA2MjEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YmYxYjllYmM5NjdkNzgxNWQ1MzAxOWQyMmQwZjAxMDA0YzE3OGMwM2M2MzUxNzM5N2M2YTg1MjA0NzZlZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTgS73R6uX767t1eaU7VphH6J0cMg5tDGuzLdhTqIew) 你好我对比了一下，发现实际上文件内容已经成功同步了过来，只是显示不出来。 从文件对比里面可以看到昨天提交到云端的内容，但是从云端拉取的数据没有落地到以上三个配置文件里面，我手动把内容复制到三个文件里面就正常显示了

可能是同步的问题？比如插件首先初始化，但是运行了一会之后，才把远端的数据同步了过来。
