### ISSUE TITLE
感知数据同步更新

### ISSUE THREAD

**Issue by primejava** [frostime/sy-bookmark-plus#27]
最近发现书签数据已经同步过来了，只是书签没有展示最新数据而已，当我重启插件或者思源之后，书签插件就会更新最新的数据          ![image](https://github.com/user-attachments/assets/3434a3b8-fdcf-426f-905e-7a9c9dc6d4aa)
你好我对比了一下，发现实际上文件内容已经成功同步了过来，只是显示不出来。
从文件对比里面可以看到昨天提交到云端的内容，但是从云端拉取的数据没有落地到以上三个配置文件里面，我手动把内容复制到三个文件里面就正常显示了

_Originally posted by @primejava in https://github.com/frostime/sy-bookmark-plus/issues/25#issuecomment-2283177170_

**Comment by frostime** [comment]
这个问题你是已经问过了吧？（看你是直接引用的之前issue里面的提问）。

你是又遇到同样的问题了还是怎么回事？

**Comment by primejava** [comment]
你好，还是同样的问题。现象是在A客户端增加的书签记录无法在B客户端展示出来，之前我以为是思源同步的问题，但现在我发现问题不在同步上，因为当我重启插件或者重启思源的话，新增的书签记录就可以正常展示了

**Comment by frostime** [comment]
> 你好，还是同样的问题。现象是在A客户端增加的书签记录无法在B客户端展示出来，之前我以为是思源同步的问题，但现在我发现问题不在同步上，因为当我重启插件或者重启思源的话，新增的书签记录就可以正常展示了

如果你说的是两个设备同时进行操作的话，那这个是正常现象，几乎所有插件都会这样。

简单来说，如果两个设备同时在进行操作；设备 A 的插件的配置文件更新后，虽然会同步到设备 B，但是设备 B 的插件并不会觉察到这种更新。

具体的技术细节你可以参考[这里](https://ld246.com/article/1723732790981#%E5%85%B3%E4%BA%8E%E5%90%8C%E6%AD%A5%E8%AE%BE%E7%BD%AE%E7%9A%84%E9%9A%90%E5%9D%91)

这个 issue 先留在这里，我后面看看有没有可能解决。现在就先尽量不要两个设备同时操作吧。

如果嫌关闭打开思源太麻烦，可以用“[开发者工具](https://github.com/zuoez02/siyuan-plugin-devtool)”插件，他提供了一个快速重载思源的按钮。

![image](https://github.com/user-attachments/assets/f7bd4e05-de58-4346-8ccb-4c82e9d15f23)

**Comment by frostime** [comment]
思源 v3.1.8 之后，更新了同步机制。理论上应该可以解决这个问题了。

https://github.com/siyuan-note/siyuan/issues/12433

简单来说，在设备 A 上更改了插件的数据后，当设备 B 同步时，会自动重载插件读取最新的状态文件。

这个 issue 暂时先关闭了。
