### ISSUE TITLE
动态查询：更改文档名后，刷新之后，文档名依然没有更新

### ISSUE THREAD

**Issue by Achuan-2** [frostime/sy-bookmark-plus#33]

**Comment by frostime** [comment]
查询都是直接调用的 SQL 接口，应该可能是思源内部还没索引完成？

你稍等一下再次刷新看看能不能查询成功。

**Comment by Achuan-2** [comment]
> 查询都是直接调用的 SQL 接口，应该可能是思源内部还没索引完成？
> 
> 你稍等一下再次刷新看看能不能查询成功。

增减文档可以直接刷新成功，但是文档名半天也刷新不成功

**Comment by Achuan-2** [comment]
感觉还是有点问题的
我用Query挂件搜索文档名是可以更新的，但是用书签增强插件就没法更新文档名

**Comment by frostime** [comment]
试了一下，确实存在这类问题。应该是前端响应式更新的问题。
