### ISSUE TITLE
我看了下sql文档, 但是似乎没太看懂, 我想问一下, 动态分组我想添加标签为todo的 我sql要咋写..

### ISSUE THREAD

**Issue by 834116404** [frostime/sy-bookmark-plus#36]

**Comment by frostime** [comment]
如果是查询 tag 标签的话用下面这个

```sql
select * from blocks where tag like '%<tag名称>#%'
```

比如这样：
![image](https://github.com/user-attachments/assets/adabddc7-b0a9-4f67-9979-8cc9aeeb77ca)

**Comment by 834116404** [comment]
select * from blocks where tag like '%todo%'
