### ISSUE TITLE
从书签打开的文档，右上角显示”退出聚焦“

### ISSUE THREAD

**Issue by pisceswb** [frostime/sy-bookmark-plus#37]
如题，从书签打开的文档，右上角显示”退出聚焦“字样，不能点击取消，而实际文档并不是聚焦模式。
聚焦一个块，然后可以点击”退出聚焦“，页面恢复正常。

**Comment by frostime** [comment]
设置里面把这个先关掉吧。
![image](https://github.com/user-attachments/assets/16617048-0203-44b7-943e-cf85f6d73487)

我后面再改一下，可能是上个版本写逻辑的时候出现疏漏了。

**Comment by pisceswb** [comment]
关闭这个选项后也不行 @frostime

**Comment by frostime** [comment]
> 关闭这个选项后也不行 @frostime

更新插件

**Comment by pisceswb** [comment]
> > 关闭这个选项后也不行 @frostime
> 
> 更新插件

请问我直接从github下载覆盖的话，会不会把以前的打开记录覆盖掉？

**Comment by frostime** [comment]
不会。
但是为什么要下载？等插件市场更新就可以了。

**Comment by pisceswb** [comment]
修复好了，谢谢！
