### ISSUE TITLE
优化判断当前文档的定位方案

### ISSUE THREAD

**Issue by TCOTC** [frostime/sy-bookmark-plus#4]
在分屏时，添加当前文档块始终添加左侧文档，需要判断页签焦点

**Comment by frostime** [comment]
这个不能算 bug，插件是根据激活中的 tab 标签页来判断的。不然的话也没法判断到底那个文档算是「当前文档」。

```ts
document.querySelector("ul.layout-tab-bar>li.item--focus");
```

![image](https://github.com/frostime/sy-bookmark-plus/assets/27268127/1dd5db6b-821b-4ce3-b440-6c1a67393677)

**Comment by TCOTC** [comment]
你得根据这个来判断当前的焦点在哪：

![image](https://github.com/frostime/sy-bookmark-plus/assets/78434827/3396f2eb-2105-44f7-912a-dc11a1dac04d)

**Comment by frostime** [comment]
> 你得根据这个来判断当前的焦点在哪：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/346841858-3396f2eb-2105-44f7-912a-dc11a1dac04d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDc2MTcsIm5iZiI6MTcyMDUwNzMxNywicGF0aCI6Ii83ODQzNDgyNy8zNDY4NDE4NTgtMzM5NmYyZWItMjEwNS00NGY3LTkxMmEtZGMxMWExZGFjMDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA2NDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YzI0YTI2OTY1MGViMjQyNmQxNmU3MjRiMTU0ZWRhNDgyOTljMmU3YjNhMjZhNTc5NzI3NTRkNGU0NmZlZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TR1aalHd11Za7styk8T_MjN2VVe4kyt40CHPCWIP3wo)

也行，可以在前面加上这个条件，先定位 active 的 wnd。
