### ISSUE TITLE
折叠展开动态书签组，将其刷新一下

### ISSUE THREAD

**Issue by pisceswb** [frostime/sy-bookmark-plus#8]
折叠展开动态书签组时，能否将该组自动刷新一下

**Comment by pisceswb** [comment]
设置了下面的显示最近修改文件的动态书签，关闭打开书签组，并不能自动刷新，但是按刷新按钮可以刷新，请问能否再改进一下，谢谢

`SELECT * FROM blocks 
WHERE type = 'd' 
ORDER BY updated DESC 
LIMIT 20;
`

**Comment by frostime** [comment]
> @frostime

这个功能默认是关闭的，要在设置里面打开

![image](https://github.com/user-attachments/assets/0caa3812-85b8-46b2-95ac-baa40f9afef2)

![recording](https://github.com/user-attachments/assets/cb539b33-cf11-4930-807b-4068b3881b09)

**Comment by pisceswb** [comment]
> > @frostime
> 
> 这个功能默认是关闭的，要在设置里面打开
> 
> ![image](https://private-user-images.githubusercontent.com/27268127/348730871-0caa3812-85b8-46b2-95ac-baa40f9afef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDEyODEsIm5iZiI6MTcyMTE0MDk4MSwicGF0aCI6Ii8yNzI2ODEyNy8zNDg3MzA4NzEtMGNhYTM4MTItODViOC00NmIyLTk1YWMtYmFhNDBmOWFmZWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMTcyODFhNjczNDIxNmU3NmUyZTM2ZWIxNThjZTY2MWRhNWE1ZDk5YmQ2MzgxZTI3NDRhMTA5NDg4Zjk2M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.42R8c0bALpEdDkuRwWBRFvwCz0c89vFpBbuV6BTdrAo)
> 
> ![recording](https://private-user-images.githubusercontent.com/27268127/348731352-cb539b33-cf11-4930-807b-4068b3881b09.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDEyODEsIm5iZiI6MTcyMTE0MDk4MSwicGF0aCI6Ii8yNzI2ODEyNy8zNDg3MzEzNTItY2I1MzliMzMtY2YxMS00OTMwLTgwN2ItNDA2OGIzODgxYjA5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzODdmNDM5YTlmOGJmNjlhZjRhNzAwYTEyNGE5YzkyZjVkNDQyMDAzZjFlZTNlODE4Njg0NTJlZTAwOWQ0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhcyx4qcxDbq9emG5qb7dqCT7YxM_rfYoCeExArx_K8) [ ![recording](https://private-user-images.githubusercontent.com/27268127/348731352-cb539b33-cf11-4930-807b-4068b3881b09.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDEyODEsIm5iZiI6MTcyMTE0MDk4MSwicGF0aCI6Ii8yNzI2ODEyNy8zNDg3MzEzNTItY2I1MzliMzMtY2YxMS00OTMwLTgwN2ItNDA2OGIzODgxYjA5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzODdmNDM5YTlmOGJmNjlhZjRhNzAwYTEyNGE5YzkyZjVkNDQyMDAzZjFlZTNlODE4Njg0NTJlZTAwOWQ0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhcyx4qcxDbq9emG5qb7dqCT7YxM_rfYoCeExArx_K8) ](https://private-user-images.githubusercontent.com/27268127/348731352-cb539b33-cf11-4930-807b-4068b3881b09.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDEyODEsIm5iZiI6MTcyMTE0MDk4MSwicGF0aCI6Ii8yNzI2ODEyNy8zNDg3MzEzNTItY2I1MzliMzMtY2YxMS00OTMwLTgwN2ItNDA2OGIzODgxYjA5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzODdmNDM5YTlmOGJmNjlhZjRhNzAwYTEyNGE5YzkyZjVkNDQyMDAzZjFlZTNlODE4Njg0NTJlZTAwOWQ0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhcyx4qcxDbq9emG5qb7dqCT7YxM_rfYoCeExArx_K8) [ ](https://private-user-images.githubusercontent.com/27268127/348731352-cb539b33-cf11-4930-807b-4068b3881b09.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDEyODEsIm5iZiI6MTcyMTE0MDk4MSwicGF0aCI6Ii8yNzI2ODEyNy8zNDg3MzEzNTItY2I1MzliMzMtY2YxMS00OTMwLTgwN2ItNDA2OGIzODgxYjA5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzODdmNDM5YTlmOGJmNjlhZjRhNzAwYTEyNGE5YzkyZjVkNDQyMDAzZjFlZTNlODE4Njg0NTJlZTAwOWQ0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhcyx4qcxDbq9emG5qb7dqCT7YxM_rfYoCeExArx_K8)

好用，赞！
